#!/bin/bash

<<Interface_Modes

 Interface: wlan1 = AP for all modes.

 ROUTER MODE:

 Access Point    (wlan1)
 Wifi Connection (wlan0)
 ETH0 = LAN "Provide a wired ethernet connection"
 ETH0 = WAN "Provide WAN Access to Connected Device"

 MESH MODE:
 Access Point    (wlan1)

 MESH Connection 
   (Wlan0 "RF"  : (Eth0 "N/A")
   (Wlan0 "RF") : (Eth0 "LAN")
   (Wlan0 "RF") : (Eth0 "WAN")
   (Wlan0 "WAN" : (Eth0 "DTD Link")

Interface_Modes

# Example Use:
# mmconfig NODEID ROUTER (LAN or WAN)
# mmconfig NODEID MESH (LAN, WAN, DTD)

echo "Change hostname to $1"

# Router Mode
if [[ $2 == "ROUTER" ]]; then 

   if [[ $3 == "LAN" ]]; then
     echo "Router with Wired Lan"
   fi

   if [[ $3 == "WAN" ]]; then
      echo "Router with WAN Feed"
   fi
fi

# Mesh Mode
if [[ $2 == "MESH" ]]; then 

   if [[ $3 == "LAN" ]]; then 
     echo "Mesh Node with Wired Lan"
   fi

   if [[ $3 == "WAN" ]]; then
      echo "Mesh Node with Eth0=WAN input"
   fi

   if [[ $3 == "DTD" ]]; then
      echo "Mesh Node with Wlan1(WAN) with Eth0= DTD Link" 
   fi
fi


