#!/bin/bash 

<<Interface_Modes

 Interface: wlan1 = AP for all modes.

 Parameters: type, Callsign, NodeId, AdminPassword, NodeCH, Eth0Mode, RouterName, WifiSSID, WifiPassword, Eth0Use, apSSID, apPASS, apCH, nodeSSID

Interface_Modes

connectWifi()
{
# Connect to Wifi
sudo nmcli dev disconnect wlan0 2>&1
sudo nmcli device wifi connect $wifiSSID password $wifiPASS ifname wlan0 2>&1
}

createAP()
{
# Build /etc/hostapd.conf file
newfile="/etc/hostapd.conf"
echo "interface=wlan1" > $newfile
echo "driver=nl80211" >> $newfile
echo "ssid=$apSSID" >> $newfile
echo "channel=$apCH" >> $newfile
echo "auth_algs=3" >> $newfile
echo "max_num_sta=10" >> $newfile
echo "wpa=2" >> $newfile
echo "wpa_passphrase=$apPASS" >> $newfile
echo "wpa_pairwise=TKIP CCMP" >> $newfile
echo "rsn_pairwise=CCMP" >> $newfile
echo "ctrl_interface=/var/run/hostapd" >> $newfile

# Restart Services
[ -f "/var/run/hostapd/wlan1" ] && rm -r "/var/run/hostapd/wlan1"
sudo /usr/sbin/update-rc.d hostapd disable
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl enable hostapd-systemd
sudo /bin/systemctl restart hostapd-systemd
}

createADHOC()
{
# Lets Calculate the IP Address via Mac Address
MACID=`ifconfig | grep wlan0 | sed 's|.*HWaddr ||'`
MAC4=`echo $MACID | cut -d : -f 4`
MAC5=`echo $MACID | cut -d : -f 5`
MAC6=`echo $MACID | cut -d : -f 6`
ip2=`printf %d 0x$MAC4`
ip3=`printf %d 0x$MAC5`
ip4=`printf %d 0x$MAC6`
net=10
nodeIP=$net.$ip2.$ip3.$ip4

echo "" >> /etc/network/interfaces
echo "auto wlan0" >> /etc/network/interfaces
echo "iface wlan0 inet static" >> /etc/network/interfaces
echo "address $nodeIP" >> /etc/network/interfaces
echo "netmask 255.0.0.0" >> /etc/network/interfaces
echo "wireless-channel $nodeCH" >> /etc/network/interfaces
echo "wireless-essid $nodeSSID" >> /etc/network/interfaces
echo "wireless-mode ad-hoc" >> /etc/network/interfaces  
}

createOLSR()
{
# Create the OLSRD Config File
echo 'DebugLevel 0' > /etc/olsrd.conf
echo 'AllowNoInt yes' >> /etc/olsrd.conf
echo 'IpVersion 4' >> /etc/olsrd.conf
echo 'MainIp' $nodeIP >> /etc/olsrd.conf
echo 'RtTable 30' >> /etc/olsrd.conf
echo 'RtTableDefault 31' >> /etc/olsrd.conf
echo 'LinkQualityAlgorithm "etx_ffeth"' >> /etc/olsrd.conf
echo 'ClearScreen     yes' >> /etc/olsrd.conf
echo -e '\n' >> /etc/olsrd.conf
echo 'Hna4' >> /etc/olsrd.conf
echo '{' >> /etc/olsrd.conf
#echo -e '\t10.138.61.176 255.255.255.240' >> /etc/olsrd.conf
echo '}' >> /etc/olsrd.conf
echo -e '\n' >> /etc/olsrd.conf
echo 'LoadPlugin "olsrd_arprefresh.so.0.1"' >> /etc/olsrd.conf
echo '{' >> /etc/olsrd.conf
echo '}' >> /etc/olsrd.conf
echo -e '\n' >> /etc/olsrd.conf
echo 'LoadPlugin "olsrd_httpinfo.so.0.1"' >> /etc/olsrd.conf
echo '{' >> /etc/olsrd.conf
echo '  PlParam "Net" "0.0.0.0 0.0.0.0"' >> /etc/olsrd.conf
echo '  PlParam "port" "1978"' >> /etc/olsrd.conf
echo '  PlParam "Resolve" "true"' >> /etc/olsrd.conf
echo '}' >> /etc/olsrd.conf
echo -e '\n' >> /etc/olsrd.conf
echo 'LoadPlugin "olsrd_txtinfo.so.0.1"' >> /etc/olsrd.conf
echo '{' >> /etc/olsrd.conf
echo '  PlParam "accept" "0.0.0.0"' >> /etc/olsrd.conf
echo '}' >> /etc/olsrd.conf
echo -e '\n' >> /etc/olsrd.conf
echo 'LoadPlugin "olsrd_jsoninfo.so.0.0"' >> /etc/olsrd.conf
echo '{' >> /etc/olsrd.conf
echo '  PlParam "accept" "0.0.0.0"' >> /etc/olsrd.conf
echo '}' >> /etc/olsrd.conf
echo -e '\n' >> /etc/olsrd.conf
echo 'LoadPlugin "olsrd_dot_draw.so.0.3"' >> /etc/olsrd.conf
echo '{' >> /etc/olsrd.conf
echo '  PlParam "port" "2003"' >> /etc/olsrd.conf
echo '  PlParam "accept" "127.0.0.1"' >> /etc/olsrd.conf
echo '}' >> /etc/olsrd.conf
echo -e '\n' >> /etc/olsrd.conf
echo 'LoadPlugin "olsrd_watchdog.so.0.1"' >> /etc/olsrd.conf
echo '{' >> /etc/olsrd.conf
echo '  PlParam "file" "/tmp/olsrd.watchdog"' >> /etc/olsrd.conf
echo '  PlParam "interval" "5"' >> /etc/olsrd.conf
echo '}' >> /etc/olsrd.conf
echo -e '\n' >> /etc/olsrd.conf
echo 'LoadPlugin "olsrd_dyn_gw.so.0.5"' >> /etc/olsrd.conf
echo '{' >> /etc/olsrd.conf
echo '  PlParam "Ping" "71.42.236.91"' >> /etc/olsrd.conf
echo '  PlParam "Ping" "71.42.236.90"' >> /etc/olsrd.conf
echo '  PlParam "Ping" "8.8.8.8"' >> /etc/olsrd.conf
echo '  PlParam "Ping" "8.8.4.4"' >> /etc/olsrd.conf
echo '  PlParam "Interval" "60"' >> /etc/olsrd.conf
echo '}' >> /etc/olsrd.conf
echo -e '\n' >> /etc/olsrd.conf
echo 'Interface "wlan0"' >> /etc/olsrd.conf
echo '{' >> /etc/olsrd.conf
echo '}' >> /etc/olsrd.conf
echo -e '\n' >> /etc/olsrd.conf
#echo 'Interface "eth0.2"' >> /etc/olsrd.conf
#echo '{' >> /etc/olsrd.conf
#echo '  Mode "ether"' >> /etc/olsrd.conf
#echo '}' >> /etc/olsrd.conf
echo 'LoadPlugin "olsrd_nameservice.so.0.3"' >> /etc/olsrd.conf
echo '{' >> /etc/olsrd.conf
echo '    PlParam "sighup-pid-file" "/var/run/dnsmasq.pid"' >> /etc/olsrd.conf
echo '    PlParam "interval" "30"' >> /etc/olsrd.conf
echo '    PlParam "timeout" "300"' >> /etc/olsrd.conf
echo '    PlParam "name-change-script" "touch /tmp/namechange"' >> /etc/olsrd.conf
echo '    PlParam "name"  "'$nodeID'"' >> /etc/olsrd.conf
echo '}' >> /etc/olsrd.conf
echo -e '\n' >> /etc/olsrd.conf
#echo 'Interface "tun50" "tun51" "tun60"' >> /etc/olsrd.conf 
#echo '{' >> /etc/olsrd.conf
#echo '     Ip4Broadcast 255.255.255.255' >> /etc/olsrd.conf
#echo '}' >> /etc/olsrd.conf

sudo ifconfig wlan0 down 
sudo iwconfig wlan0 mode ad-hoc channel $nodeCH essid $nodeSSID
sudo ifconfig wlan0 up $nodeIP
}
# Start of Script
clear
#if [[ $# -eq 0 ]]; then checkInterfaces; fi

request=$1

if [[ $request == "check" ]]; then 
   if [[ $2 == "installed" ]]; then [ -e "/var/www/html/.installed" ] && echo "TRUE" || echo "FALSE"; fi
   if [[ $2 == "ethernet" ]]; then [ -d "/sys/class/net/eth0" ] && echo "TRUE" || echo "FALSE"; fi
fi

# Get all Parameter Values
  callsign=$2
  nodeID=$3
  adminPASS=$4
  nodeCH=$5
  nodeEthMode=$6
  shift; shift; shift; shift; shift; shift;
  routerName=$1
  wifiSSID=$2
  wifiPASS=$3
  routeEthMode=$4
  apSSID=$5
  apPASS=$6
  apCH=$7
  nodeSSID=$8

# Router Mode
if [[ $request == "microrouter" ]]; then  

  echo "Router [$routerName]"
  echo "Wifi [$wifiSSID]"
  echo "WifiPassword [$wifiPASS]"
  echo "Eth Mode [$routeEthMode]"
  echo "AP [$apSSID]"
  echo "AP-Pass [$apPASS]"
  echo "AP-CH [$apCH]"
  echo

  wlanIP=`ifconfig wlan1 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1`
  echo -e "127.0.0.1\tlocalhost" > /etc/hosts
  echo -e "$wlanIP\t$routerName" >> /etc/hosts
  echo "::1       localhost ip6-localhost ip6-loopback" >> /etc/hosts
  echo "ff02::1   ip6-allnodes" >> /etc/hosts
  echo "ff02::2   ip6-allrouters" >> /etc/hosts
  echo $routerName > /etc/hostname

  /etc/init.d/dnsmasq restart
  connectWifi
  createAP
fi

# Mesh Mode
if [[ $request == "micromesh" ]]; then 

  echo "Callsign [$callsign]"
  echo "NodeID [$nodeID]"
  echo "Admin Password [$adminPASS]"
  echo "Node Channel [$nodeCH]"
  echo "Node Ethernet Mode [$nodeEthMode]"
  echo "Node SSID [$nodeSSID]"
  echo
  echo "Router [$routerName]"
  echo "Wifi [$wifiSSID]"
  echo "WifiPassword [$wifiPASS]"
  echo "Eth Mode [$routeEthMode]"
  echo "AP [$apSSID]"
  echo "AP-Pass [$apPASS]"
  echo "AP-CH [$apCH]"
  echo

  createAP
  createADHOC
  createOLSR

  sudo chgrp -R www-data /etc/olsrd.conf
  sudo chmod g+w -R /etc/olsrd.conf

if [ -L /etc/resolv.conf ]; then
    rm -f /etc/resolv.conf
    touch /etc/resolv.conf
fi

  sudo bash -c "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"


fi
