#!/bin/bash

# *  SSID              MODE    CHAN  RATE       SIGNAL  BARS  SECURITY 

nmcli device wifi list ifname wlan0 > /tmp/wifilist

printf "<table>"


while read SSID MODE CHAN RATE UNITS SIG BARS SECURITY ; do


if [ "$SSID" == "*" ] ; then
	printf "<tr><th>SSID</th><th>Mode</th><th>Ch.</th><th>Rate</th><th>Signal</th><th>Bars</th><th>Security</th></tr>"
fi

if [ "$SSID" != "--" ] && [ "$SSID" != "*" ] ; then

  printf "<tr>\n"
  printf "<td>$SSID</td>\n"
  printf "<td>$MODE</td>\n"
  printf "<td>$CHAN</td>\n"
  printf "<td>$RATE $UNITS</td>\n"
  printf "<td>$SIG</td>\n"
  printf "<td>$BARS</td>\n"
  printf "<td>$SECURITY</td>\n"
  printf "</tr>\n\n"
fi

done </tmp/wifilist

printf "</table>"

rm /tmp/wifilist

