#!/bin/bash
# *  SSID              MODE    CHAN  RATE       SIGNAL  BARS  SECURITY

if [[ $# -eq 0 ]]; then echo -e "Available Parameters are AP or MESH\n\n"; exit 1; fi
if [[ $1 == "AP" ]]; then mode="Infra"; fi
if [[ $1 == "MESH" ]]; then mode="Ad-Hoc"; fi
if [[ $2 != "HTML" ]]; then 
   nmcli -f SSID,MODE,CHAN,SIGNAL,BARS d wifi list | grep $mode | egrep -v "^--|Apple" | sort | uniq 
   exit 0
else
   nmcli -f SSID,MODE,CHAN,SIGNAL,BARS d wifi list | grep $mode | egrep -v "^--|Apple" | sort | uniq > /tmp/wifilist
fi


printf "<table>"
printf "<tr><th>SSID</th><th>Channel</th><th>Signal</th><th>Bars</th></tr>"
while read SSID MODE CHAN SIG BARS ; do

	if [ "$SSID" == "*" ] ; then
        printf "<tr><th>SSID</th><th>Mode</th><th>Ch.</th><th>Rate</th><th>Signal</th><th>Bars</th><th>Security</th></tr>"
	fi

	if [ "$SSID" != "--" ] && [ "$SSID" != "*" ] ; then

  		printf "<tr>\n"
		printf "<td><a href=\"#page_configure\" class=\"ui-btn\" onclick=\"document.getElementById('ssid').value='$SSID'\">$SSID</a></td>\n"
		#printf "<td><a href='#page_configure' class='ui-btn'>$SSID</a></td>\n"
  		printf "<td>$CHAN</td>\n"
  		printf "<td>$SIG</td>\n"
  		printf "<td>$BARS</td>\n"
  		printf "</tr>\n\n"
	fi

done < /tmp/wifilist

printf "</table>"

rm /tmp/wifilist
